version: "3.9"
services:
  web:
    build: .
    volumes:
      - .:/code
    ports:
      - "5000:5000"
    command: [ "0.0.0.0:5000" ]
    depends_on:
      - redis
      - firefoxdriver
    restart: always
  firefoxdriver:
    image: selenium/standalone-firefox:104.0-geckodriver-0.31-20220831
    ports:
      - "4444:4444"
    hostname: "firefoxdriver"
  redis:
    image: "redis/redis-stack:latest"
    ports:
      - "6379:6379"
      - "8001:8001"
      