# Generated by Django 4.0.5 on 2022-06-25 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableAnalyzeCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_news', models.DateField(verbose_name='Дата новости')),
                ('name_news', models.TextField(verbose_name='Имя информационного ресурса')),
                ('name_title_news', models.TextField(verbose_name='Наименование заголовка новости')),
                ('url', models.URLField(verbose_name='Ссылка на новость')),
                ('category', models.TextField(verbose_name='Категория инвестиционной активности')),
                ('company_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.company', verbose_name='Наименование предприятия/организации')),
            ],
            options={
                'verbose_name': 'Таблица',
                'verbose_name_plural': 'Таблицы',
            },
        ),
    ]
